
// This URL should be replaced with the one generated by your Google Apps Script deployment
const GOOGLE_SCRIPT_URL = localStorage.getItem('darts_sheet_url') || '';

export const uploadGameStats = async (data) => {
    if (!GOOGLE_SCRIPT_URL) {
        console.warn('No Google Sheet URL configured. Data not uploaded.');
        // Prompt user to set URL if missing
        const url = prompt('Please enter your Google Apps Script Web App URL to save stats (or cancel to skip):');
        if (url) {
            localStorage.setItem('darts_sheet_url', url);
            return uploadGameStats(data); // Retry
        }
        return;
    }

    try {
        // We use no-cors mode because Google Apps Script redirects, which fetch doesn't handle well with CORS in simple mode sometimes,
        // but actually for POST requests to work and return data we usually need 'cors'.
        // However, standard Apps Script Web App setup allows CORS if we return correct headers.
        // For simplicity, we'll try standard POST.

        const response = await fetch(GOOGLE_SCRIPT_URL, {
            method: 'POST',
            mode: 'no-cors', // 'no-cors' is often safer for simple fire-and-forget to Sheets
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(data)
        });

        // With no-cors we can't check response.ok
        console.log('Request sent to Google Sheets');
    } catch (error) {
        console.error('Error uploading to Google Sheets:', error);
        throw error;
    }
};
